dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test-with-coverage-lcov

after_success:
  - npm run upload-coverage

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true

