dist: xenial
language: node_js

env:
  global:
  - secure: JJLXB6mQ/q2zL3TEWXhNz5hYk4yn2hcXKwZPDldGS9On+KdDyTTQMw9apTR0pYeIggzZTSFueJNkUqOnrFJ6gaaByB1zGmquB0Vw3FKmXppUIQjEW6JR+tbKHXdkp3Bz91Bl2EXDDUjX+UvzhYvYkNf87BflhT05JDQqxPQ3t6jviLXChKM7+PZZKiXWjtBPZoPvlYZnZftQa4Gj9b0S8yuW9nWJx7X7DIqMWMNWsoNsHsZeXPDQzQp2Q0zCkHSZw107YbwMUSgJCvN4jefpXq/MW6mDU2Z/eL6cDO/iT5GVwffe/gb/94MMI+I9va4/RVkz69kR9II2meP0G34vLbe6RWm0OC2nIsq5xnsYkHGBveSge5lyqWBkAZyTJeuCQ5SKIomke+XsH3g7v3eqWsOZ+CBtYpGkYShr4lNOBMIUF2TckL6vmt+6eFccuf9fxwZTYLUKutuvtLQF5levV/gZl8rSO2Fi5SxyGRna8GaWBevUcZ6ikL7LgJfZClYH8xHlI3v9yznnad0VkQFFgKJf4tZZwqG7FdtJZTfIFNNlLUBiGcHlYwMEbwPF9SRfdP05LwaUERxXH61afFexx7p6cnlZXTIGuFdSJNXmH0AiiNPofBg9EzmX3m+gnVhlH9ENJcgbNdjkQItT5uGIUjxY+UaTTpUPTnTF9EP6lZk=
  - secure: hx4nCxX8IrQQoXmvVIJS1OrYntqL/64jhfeduNdU+087UI6rKHnl3z+A1j6xgkk4wPwV0Y/JASpOCf6DRFu/c0yjehhPOrJFubwy9Aq7Td3r5VjGVs6k1phDIk7fVmXfYf4VCTRcs9LqOwIBri6ByfMm5fpkqJ2rcWA2/WwHVglznhgwhR4pCQTgZnqBH/o9Fk3kTZHDk1jt2udCfzirngIa7RnzIBwHGpXRPE1ZO7aawY7zIFXePjwKUjExOKGUyj1RTvurYnPsXzUBGQrWQ2NrMjAayMZZDfk8aqjihtOxIvgw6FQ5tdXvxeHkeLHe6LLZ1vogAyfoPN8JpV0ZmH2dkNfc5MVRAkd8iW0zpTMT8vuJeReodf4e6/koNdzKOPSWdh63m1pepDy4pfLZRrcbRxCAmnLZ5hHpUT+0TmmiEIiOLmVyKFKLJEmevuJPhm7iUi/UhEA9gkdXgsivzmsYoAItzClmiBDfiy0ILiYtgYeoEkxd+yeWtYP1XuAtnTqATLG8Y7oqyX7NOqPtgSE1mzwCVu3uVNrsd2L8lIw46cvFjr6yZzGNOAxH8MszlwfU1WRJWSJHykxrEiuWnh9YYLtZF4Us1D3SKGT4ja5sFTOwTqZE5tfrOn7Ycn0BmQXVYm5C6JR+ihk4yrGN2sb3qV1Q+AFwPW7NXNV0Keo=

install:
  - npm ci
script:
  - npm run build
  - npm run test
  - echo "sleep random number of seconds 1-10 to prevent blockchain collisions" && sleep "$(( ( RANDOM % 10 )  + 1 ))"
  - npm run verify

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
