dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true

env:
  global:
  - secure: HHwrVRUnlPbHjKCy87Iwg6Og4s3v7McoC31qNWGMXyUNG6fQu3ekMu7vNZ8hHfpMYaPzqmTC4fnWUUjVSdVTAmQfkWCRtio1c/Y0jYXHXv/B27G+FuB/ZYt3mJBzBOVrCqdY9nCCYnv6uSMkTW8w+W79Jb6pKhf1yjc9Sauj1Z+LsoUv2aIwuspf6mJwQ22P8PdQj1KHN//h25OroWQmYeuxeAWSwMWE72BXScwCewOxkF7ZhkNSSxA+GrLmz37S3a0B3Kjj4xLX+nEqANYwNeB2LIqKgrIUYM3p+p0za6YcmbFNIHm4csjL0mtNUthEGQ2MwXMJ5bYGevnPgP6/riyHfWZaAnlDVcnhkhFXY3t+GLnrrd46KtCJO23QaPnUUijw+NexBqHo9GdlYZUuSLrAtBekNQS2710ZYKQf3McamzBVJIAnliBXtoSCnV+SLuz3snu2fIqSWSzwlczAhSiJxFBvpLAbQIFRRpgFvJGNzJcvwOc8+QXpu5fzFtgqAC0s/VQ86x2DQ8H1tRo3Xd+sKVuKqG+ya7GU0CSkIS52g9lTBiq3QBhQ32wnirfM/2p3q1uUVDX2acenIFhuX6ziVjlc2JagJ4eRMHQcPDn1RZ2hqHWa+GpLCHLNfzn/rIeci6FWyycM1D11PIZIegtEgbyBkxzL2KsgzuJmemo=
  - secure: lHQue0cGFbsshl8cTwG46bB9A2X3C9siB9Xsc4sQL6kPc7tRE63aEG2pZrxTxlr+jxRRHvmV8UjlHzmLa5cxTzmOArDtSFlC9RR/2utPg2JcEkpwPs9JAiOMQVEld4gzcXzwVmNYAjFCAOLChmvWtKYdNmftEJC1z8GiYiuh+6GnPM7fM7PXc5RH0UHKKK2HB8irFzjaN5pmgZ3MR2hz/fdVwY5Lm7JwKkYpaGr9yqO/En6aC0tkxFVz+a+ExV7rIzFlP2pcp29uF6Qr5kO2xCQwLPMxW6F2nd3f03nx8IqebUl0orZBfCr/9lmHJTI81q7CuT3bsSnypXHtQCkPiouiaVv1PROB/QWHqDp5LJ9yRhVFsz9m8EiAmKyiRqH7XjA7f8sHdgjcq6YN2vAFtla3SmCd22jpf3CurKrvjv0D4tH6q49ci9Md+3wrRi9cEkEFCE7Y+wkACINQ+WHnrWxKDxR7tpZEnGjP0bTw9tbSu6A3d5vPuenXckQSxKsJm3T5K0rleyyUdSwm4WsJ0zSa3I+jiMLagZtNZ05dMV8N9swqqUFauW2ksNIHjwawvN3jy6jb7MCBYFifaR3PRqwWBK/gNgZkwMBE75zNvY2pRnT8kCj92XatUKN1Z+e3+oyw9VhGuHtpDwtHMzouNxi74ZzklBLen/yBarUh5Lo=
