dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true

env:
  global:
  - secure: hT6eV7F3Hz0GPpDOKnyA+N8lLHnI6LYl1SfotZZ3H+PgsvsjxeMfWhz8EYBBsuUBhulPyMzA1Fi7hPEABZFdhqgdLfV6Hnz896Hh+Lt4946U9IXxPGOjdnokFKCr15cNitrbSdbGgZvWtCnxm4c4w+yAloE7ms8/eBN5RqjHg8fbyGguIxA+66y4TPts020wACzHxwwH+A9rSpPfTox7+U79l8ZA7dxVH6y6cCetdHWHK9iKrSZQ+VYttauJhJSniA48l4E3sTnOFXpNhc2wyRE6kbzKCjMwkysTd1Lz/yjEI2CeInxjTZKZqDgQ7JT7TbEi7qAqSCo/suBDrOOciBP/GHhk2SWp0amwTQ0M4ggPBUiYqUP81XcgZiGwzlgJ0ZB5C6WvwAD7p7RzzChcsda9e4Q4uVBpC/tjn/gzhN+F+nZZX1ZYV8k7/qi4putYjopCgf7oSVn2by77MNys0yV2CKfJITpyLoeqgfucum8NgekkhNd7NBGVtB61fZi2Pize34n0t6mEPaN0gYU+VXe2JGyDiexoIUjniL1SHTPX5GXmwG7e1Pvxy4/8en8EEzE0YEWe1WUEQ1BoLE2s94pyovIcZ9JRSHvM6Zrv63j2jdtGxN4K1IBnIbFFvG5siwySDhDcJmtXJikoVCaOiNVOIDe2VeCKtU5gnEm7DUs=
  - secure: bUVQ3/NxduiZk8IumXxRFkUcHdKE5WwGUIUAVt/OVHvb6h2gBJD/jnqL9/2MbVnnj4E/XHwmo8unDd2kpQd0hkRrQJ5/r9tFl0nAcCHHr4DH0Nr/Fm2OLB+kHtdLJioarVwh5ANWsC8fwW1P6RS4vY4ixL93416EWJ2s4fTYMz1LfNPLwh8FwZS7JctbGVlSJD3ennFFExRqGAfSgRPITxJSQIIAgytMBLwHWlPlakRrDrbkCtU9pimI+TDVjr++Sk52aLpEnkzMgWNN5V40TTSt5S4EAMyvcEQdTArNVgFHOzo8tBoipd4hD1oIRHb84wv+x1Ix/JR8uJVYZiW1Q560K2ANzLD7MCPs89+zi8KKNdjidgNl5ZEaUSWF1uwY0LQf8Y9CwHM/KzTfQZ/6MXAZ7iv0aoSD93QQ/QvBeFltHbxutR3R/e1x9BqFb03cb6UQj9TMJbN+uWZz/CZkmxTOKU0Wze6OTBHtIWYRAjzJWFMjoNuGsZn12vNZLczyJhl+6U+qxvlG5iqtJqtHttbL9BuK3TIEI1RcbzlGtuJ0q7rR7F7USpPX6WIzVE601x03yzhC/Ck94O6UILg+W6NYwPwqecJS4bxbi0/FqkApI597+6t+CKBydUZcRoBv6KY9lFoM2nCN5CY4rkfmgILWpmIAQy3xk9X6l4iLkLI=
